### ISSUE TITLE
Shares disappear after delegation in v2

### ISSUE THREAD

**Issue by lumberg** [HausDAO/daohaus-app#186] opened 2020-04-16 21:33 UTC
After I delegated, I couldn't vote on either the original account nor the delegated account due to having 0 shares on both addresses.  Error I get is: _You must have valid DAO shares to vote._

Member address: 0x717303f9258ff6fae98a9e1dba3d34bf21688415
Delegate address: 0x340d2c6279b30f5FA4963e3CD10c82425a217a04
Delegate txid: https://etherscan.io/tx/0x48c8c14002ee26eb10e8de9982d94b515e2f41071c85cf2c579a98092dcea8de

**Comment by plor** [comment] 2022-05-19 19:55
I wasn't able to reproduce this, looks like it was fixed in the intervening time. If someone is able to document the steps to reproduce this, please re-open this issue and add those details.

**Closed by plor** 2022-05-19 19:55 UTC
Labels: bug, voting
